### ISSUE TITLE
Please reduce the verbosity of triggeralgs debug statements that are ON by default

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/triggeralgs#20]
The routines in the triggeralgs package are using direct TRACE includes and calls instead of using the Logging package.  This should be fixed.

**Comment by philiprodrigues** [comment]
We did it this way because `triggeralgs` is intended to hold the trigger algorithms that we may want to also run in the offline framework. So `triggeralgs` can only depend on packages that are available in offline world. Setting up `dunetpc` gives me `TRACE`, but not the daq logging package. But if `logging` can be included in the offline setup, we could use it (which would certainly be nicer than using raw TRACE)

**Comment by bieryAtFnal** [comment]
Ah, yes, sorry for forgetting that.  

Let me change the title and content of this Issue to contain what I _really_ would like to request...

Debug messages from several trigger algorithms (e.g. TriggerActivityMakerPrescale) are unnecessarily cluttering up the TRACE logs because they are so prevalent.  

I would like to request that logging statements like 

- TLOG_DEBUG(TRACE_NAME) << "Emitting prescaled TriggerActivity " << (m_primitive_count-1);

use a debug level greater than zero so that they are **off** by default.

**Comment by bieryAtFnal** [comment]
It looks like a start on doing this might already be on the _philiprodrigues/reduce-logging_ branch...

**Comment by bieryAtFnal** [comment]
The changes requested in this Issue have long been included in the code, so I'll close this stale Issue.
